language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "0.8"
  - "iojs"
  - "iojs-v2"
  - "iojs-v1"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libasound2-dev
# Waiting on these two packages to get whitelisted so we can move to a fully
# package based build:
# - https://github.com/travis-ci/apt-package-whitelist/issues/863
# - https://github.com/travis-ci/apt-package-whitelist/issues/864
before_install:
 - sudo apt-get install alsa-utils alsa-oss
install: true
notifications:
  email: false
# Travis has no snd-dummy driver (https://github.com/travis-ci/travis-ci/issues/1754)
# so our tests won't run. We run `npm install` as the test script so build errors
# appear as test failures.
script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - $CXX --version
  - npm install
